name: Load secrets from 1Password
description: Make secrets from 1Password Connect available as environment variables in the next steps.
author: 1Password
branding:
  icon: lock
  color: blue
inputs:
  version:
    description: Version of the 1Password CLI to install
    default: latest
  unset-previous:
    description: Whether to unset environment variables populated by 1Password in earlier job steps
    default: "false"
  export-env:
    description: Export the secrets as environment variables
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
