name: Load secrets from 1Password
description: Make secrets from 1Password Connect available as environment variables in the next steps.
author: 1Password
branding:
  icon: lock
  color: blue
inputs:
  unset-previous:
    description: Whether to unset environment variables populated by 1Password in earlier job steps
    default: false
runs:
  using: composite
  steps: 
    - run: |
        export INPUT_UNSET_PREVIOUS=${{ inputs.unset-previous }}
        ${{ github.action_path }}/entrypoint.sh
      shell: bash
