name: Load secrets from 1Password
description: Make secrets from 1Password Connect available as environment variables in the next steps.
author: 1Password
branding:
  icon: lock
  color: blue
inputs:
  unset-previous:
    description: Whether to unset environment variables populated by 1Password in earlier job steps
    default: "false"
  export-env:
    description: Export the secrets as environment variables
    default: "false"
  convert-ssh-keys:
    description: Convert SSH private keys from PKCS format to OpenSSH format. 1Password stores SSH keys in PKCS8/PKCS1 format, but some tools require OpenSSH format. Requires ssh-keygen to be available.
    default: "false"
  version:
    description: Specify which 1Password CLI version to install. Defaults to "latest".
    default: "latest"
runs:
  using: "node20"
  main: "dist/index.js"
