// AUTO-GENERATED by scripts/update-fallback-versions.mjs — do not edit by hand.
// Last-resort CLI versions, used only when both app-updates and Docker Hub are
// unavailable. Refresh with `npm run op-version` (see release docs).
import { ReleaseChannel } from "./constants";

export const FALLBACK_VERSIONS: Record<ReleaseChannel, string> = {
	[ReleaseChannel.latest]: "2.38.1",
	[ReleaseChannel.latestBeta]: "2.39.0-beta.02",
};
